// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1ODZpulQVVxSB4Vei0AGAnHrxvDNKP4',
    appId: '1:811652773194:web:a4cc5179663d246f2cfdb3',
    messagingSenderId: '811652773194',
    projectId: 'gymapp-cd84c',
    authDomain: 'gymapp-cd84c.firebaseapp.com',
    storageBucket: 'gymapp-cd84c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10D9rKfSlITyZfLvKGVlVTocUVrzAbFQ',
    appId: '1:811652773194:android:fff401ad1dc8c2e82cfdb3',
    messagingSenderId: '811652773194',
    projectId: 'gymapp-cd84c',
    storageBucket: 'gymapp-cd84c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAChlweKqE-eFc3xPoBYn4KuG5iEMlAUYo',
    appId: '1:811652773194:ios:a5c3b3cd0d05c90a2cfdb3',
    messagingSenderId: '811652773194',
    projectId: 'gymapp-cd84c',
    storageBucket: 'gymapp-cd84c.appspot.com',
    iosClientId: '811652773194-11llprapd1fo6r5co51andhno13c9mpg.apps.googleusercontent.com',
    iosBundleId: 'com.gymapp.gymapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAChlweKqE-eFc3xPoBYn4KuG5iEMlAUYo',
    appId: '1:811652773194:ios:2de657cd317ce59c2cfdb3',
    messagingSenderId: '811652773194',
    projectId: 'gymapp-cd84c',
    storageBucket: 'gymapp-cd84c.appspot.com',
    iosClientId: '811652773194-nbcdjih0ic9pincu1l37sh5lesahj3p4.apps.googleusercontent.com',
    iosBundleId: 'com.gymapp.gymapp.RunnerTests',
  );
}
